use_frameworks!

platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'GGQQSDKManager_Example' do
  pod 'GGQQSDKManager', :path => '../'

  target 'GGQQSDKManager_Tests' do
    inherit! :search_paths

    
  end
end
